name: ospike
on: [push]
jobs:
  run:
    name: Tests
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        ocaml-version: ["4.07.0", "4.08.1"]
    steps:
      - name: Checkout code
        uses: actions/checkout@master
      - name: Use OCaml ${{ matrix.ocaml-version }}
        uses: avsm/setup-ocaml@v1.0
        with:
          ocaml-version: ${{ matrix.ocaml-version }}
      - run: opam pin add ospike.dev -n .
      - run: opam depext -yt ospike
      - name: Install Deps
        run: opam install -t . --deps-only
      - name: Build
        run: opam exec -- dune build
      - name: Test
        run: opam exec -- dune runtest